#include<iostream>
using namespace std;
int main()
{
	cout<<" Data type      Number of bytes "<<endl;
	cout<<"-----------    -----------------"<<endl<<endl;
	cout<<" char                "<<sizeof(char)<<endl;
	cout<<" int                 "<<sizeof(int)<<endl;
	cout<<" short int           "<<sizeof(short)<<endl;
	cout<<" long int            "<<sizeof(long)<<endl;
	cout<<" bool                "<<sizeof(bool)<<endl;
	cout<<" double              "<<sizeof(double)<<endl;
	cout<<" float               "<<sizeof(float)<<endl<<endl;
	return 0; 
}